### ISSUE TITLE
编译的时候 提示语法错误

### ISSUE THREAD

**Issue by jamesInherit** [wuyanwuyan/wechart-articles-crawler#2]
app.use(async function(ctx, next) {
        ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Projects\weiapp\article\index.js:4:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechart-articles-crawler-based-anyproxy@1.0.0 start: `node index`
npm ERR! Exit status 1

**Comment by jamesInherit** [comment]
兄弟能留下QQ，或者微信联系方式吗？
